[features]
skip-lint = false

[programs.localnet]
candle_markets = "9fAJRwzjj7dBMt7fimMo6jKwwsYFD4k9eoMPD8MwBnWb"

[programs.devnet]
candle_markets = "9fAJRwzjj7dBMt7fimMo6jKwwsYFD4k9eoMPD8MwBnWb"

[provider]
cluster = "devnet"
wallet = "/home/siphonite/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"

